// SPDX-FileCopyrightText: 2025 Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT License,
// the text of which is available at https://opensource.org/license/mit
// or see the "LICENSE.txt" file for more details.
//
// Authors: See CONTRIBUTORS.txt

/*
 * API Product_Catalog
 * ODACA Product Catalog managment API Defined from *** TMF620 - Product Catalog Management API ** V4.0 version  Only a subset of TMF resources are managed in ODACA V1: - ProductSpecification - ProductOffering - ProductOfferingPrice  Added new resource to manage Product Configuration Specification (to be link with stock item).
 *
 * OpenAPI spec version: 1.0.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.orange.discobole.productcatalog.productspecification.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.datatype.jsr310.deser.key.OffsetDateTimeKeyDeserializer;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.annotation.Generated;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * A period of time, either as a deadline (validTo only) a validFrom
 * only, or both
 */
@ApiModel(description = "A period of time, either as a deadline (validTo only) a validFrom only, or both")
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-30T16:59:05.795+05:30")
public class TimeRange {
	@JsonProperty("validTo")
	@JsonFormat(shape = JsonFormat.Shape.NATURAL, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSX")
	@JsonDeserialize(keyUsing = OffsetDateTimeKeyDeserializer.class)
	private OffsetDateTime validTo = null;

	@JsonProperty("validFrom")
	@JsonFormat(shape = JsonFormat.Shape.NATURAL, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSX")
	@JsonDeserialize(keyUsing = OffsetDateTimeKeyDeserializer.class)
	private OffsetDateTime validFrom = null;

	public TimeRange validTo(OffsetDateTime validTo) {
		this.validTo = validTo;
		return this;
	}

	/**
	 * 
	 * @return validTo
	 **/
	@ApiModelProperty(value = "")
	public OffsetDateTime getValidTo() {
		return validTo;
	}

	public void setValidTo(OffsetDateTime validTo) {
		this.validTo = validTo;
	}

	public TimeRange validFrom(OffsetDateTime validFrom) {
		this.validFrom = validFrom;
		return this;
	}

	/**
	 * 
	 * @return validFrom
	 **/
	@ApiModelProperty(value = "Start of the time period, using IETC-RFC-3339 format. If you define a start, you must also define an end")
	public OffsetDateTime getValidFrom() {
		return validFrom;
	}

	public void setValidFrom(OffsetDateTime validFrom) {
		this.validFrom = validFrom;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		TimeRange timeRange = (TimeRange) o;
		return Objects.equals(this.validTo, timeRange.validTo)
				&& Objects.equals(this.validFrom, timeRange.validFrom);
	}

	@Override
	public int hashCode() {
		return Objects.hash(validTo, validFrom);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class TimeRange {\n");
		sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
		sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
