// SPDX-FileCopyrightText: 2025 Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT License,
// the text of which is available at https://opensource.org/license/mit
// or see the "LICENSE.txt" file for more details.
//
// Authors: See CONTRIBUTORS.txt

/*
 * API Product_Catalog
 * ODACA Product Catalog managment API Defined from *** TMF620 - Product Catalog Management API ** V4.0 version  Only a subset of TMF resources are managed in ODACA V1: - ProductSpecification - ProductOffering - ProductOfferingPrice  Added new resource to manage Product Configuration Specification (to be link with stock item).
 *
 * OpenAPI spec version: 1.0.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.orange.discobole.productcatalog.catalog.constant;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets SupportEntity
 */
public enum SupportEntity {

	CFSSPEC("CFSSpec"),

	STOCKITEMTYPE("StockItemType"),

	SUPPLIERPRODUCT("SupplierProduct"),

	PRODUCTSPEC("ProductSpec");

	private final String value;

	SupportEntity(String value) {
		this.value = value;
	}

	@JsonCreator
	public static SupportEntity fromValue(String text) {
		for (SupportEntity b : SupportEntity.values()) {
			if (String.valueOf(b.value).equals(text)) {
				return b;
			}
		}
		return null;
	}

	@JsonValue
	public String getValue() {
		return value;
	}
	@Override
	public String toString() {
		return String.valueOf(value);
	}
}
