# Software Name: process-flow
# SPDX-FileCopyrightText: 2025 Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT License,
# the text of which is available at https://opensource.org/license/mit
# or see the "LICENSE.txt" file for more details.
#
# Authors: See CONTRIBUTORS.txt
# Software description: The TMF701 ProcessFlow API allows management of business process definition and execution. \\r\\n\\r\\nThis API is used as a Java library in the Order Capture Management and Orchestration Delivery Fallout Management APIs.\\r\\n\\r\\n\\r\\n

app:
  version: @project.version@
  name: @project.name@
  description: @project.description@
  ownerName: Herve Bouvier
  ownerMail: herve.bouvier@orange.com

spring:
  config:
    activate:
      on-profile: default
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  cloud:
    config:
      enabled: true
  
   
logging:
  level:
    com.orange.discobole.processflow: INFO
axon:
  axonserver:
    enabled: true

process-flow:
  role:
    admin: disco-admin

---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog
      username: root
      password: root
  mongo:
    database-name: catalog
    token-store:
      enabled: true
    saga-store:
      enabled: true
    event-store:
      enabled: true
  cloud:
    config:
      enabled: false

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    enabled: false