# SPDX-FileCopyrightText: 2025 - 2026 Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT License,
# the text of which is available at https://opensource.org/license/mit
# or see the "LICENSE.txt" file for more details.
#
# Authors: See CONTRIBUTORS.txt

sonar.projectKey=com.orange.disco.ordermanagement:om-selfcare
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/*.test.{js,jsx}
sonar.exclusions=src/index.js,src/**/*.test.jsx
#sonar.exclusions=src/**/*.test.jsx,nginx/**,**/*.json,jest.config.js,helm/**,env/**,Dockerfile,CHANGELOG.md,bumpversion.sh,bumptosnapshotversion.sh,**/.releaserc.yml

sonar.javascript.lcov.reportPath=./coverage/lcov.info
sonar.testExecutionReportPaths=./coverage/report.xml