{{- if .Values.registryCredentials.create -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: diod.hostmodeui-tech-pull-token-{{ .Values.environmentType }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hostmodeui.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "hostmodeui.regcredData" . }}
{{- end }}
