version = 1

[[annotations]]
path = [ 
  "helm/.helmignore",
  "helm/templates/*.txt",
  "helm/templates/*.tpl",
  "helm/templates/*.y*l", 
  "helm/chart/templates/*.txt",
  "helm/chart/templates/*.tpl",
  "helm/chart/templates/*.y*l", 
  "helm/tool/README.md.gotmpl",
  "**/ingress.yaml",
  "mvnw",
  "mvnw.cmd",
  ".prettierrc",
  "**/banner.txt",
  "**/robots.txt",
  "**/*.avif",
  "**/*.bru",
  "**/*.csv",
  "**/*.eot",
  "**/*.ico",
  "**/*.jar",
  "**/*.jpeg",  
  "**/*.jpg",
  "**/*.json",  
  "**/*.map",
  "**/*.md",
  "**/*.mdx",
  "**/*.mp4",
  "**/*.png",
  "**/*.PNG",
  "**/*.pdf",   
  "**/*.svg",
  "**/*.robot",
  "**/*.template",
  "**/*.tgz",
  "**/*.ttf",
  "**/*.woff",  
  "**/*.woff2",
  "**/*.zip",  
  "renovate.json",
  "postman/Wiremock_server.postman_collection.json",
  ".gitleaksignore",
  "lombok.config",
  "**/*.feature",
  "docs/css/boosted.min.css.map",
  "lychee.toml.old",
  "MAINTAINERS",
  "**/THIRD-PARTY.txt",
  "NOTICE.txt",
  "DCO.txt",
  ".mvn/jvm.config",
  "**/spring.factories",
  "**/*.Dockerfile",
  ".idea/*.*",
  "**/*.postman_collection",
  "**/*.postman_environment",
  ".githooks/*",
  "**/*.drawio",
  "nginx/*.conf",
  "components/footer.astro",
  ".generatelicensefile",
  "env/.*",
  ".env",
  "profile.jfr"
 ]
SPDX-FileCopyrightText = "2022-2025 Orange SA"
SPDX-License-Identifier = "MIT"
