# SPDX-FileCopyrightText: 2025 - 2026 Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT License,
# the text of which is available at https://opensource.org/license/mit
# or see the "LICENSE.txt" file for more details.
#
# Authors: See CONTRIBUTORS.txt

---
$id: "https://orange.com/productOrderAttributeValueChangeEvent.yaml"
$schema: "http://json-schema.org/draft-07/schema#"
title: "ProductOrderAttributeValueChangeEvent"
type: "object"
allOf:
  - $ref: "../baseEvent.yaml"
extends:
  $ref: "../baseEvent.yaml"
properties:
  event:
    $ref: "productOrderAttributePayloadEvent.yaml"
required:
  - "event"