*** Settings ***
Resource        ../Keywords/post_usecases.robot

Library    RequestsLibrary
Library    OperatingSystem
Library    String
Library    BuiltIn
Library    Collections



*** Test Cases ***

Test Valid POST Request With Valid Data
    [Documentation]    Test la requête POST avec un corps valide pour `ValidityCharacteristic`.
    Get_token
    ${response}=    Post_valid_return_response    Post_body_for_ValidityCharacteristic
    Should Be Equal As Numbers    ${response.status_code}    201
    Should Contain    ${response.text}    ValidityCharacteristic
    Should Contain    ${response.text}    Id generated by automation

Test POST Request With Invalid ValidTo In The Past
    [Tags]  Bug
    [Documentation]    Test la requête POST avec `validTo` dans le passé.
    Get_token
    ${response}=    Post_invalid_ValidityCharacteristic    Test_Cases/Product/Data/Post_body_for_ValidityCharacteristic.json    validTo    400    "Invalid date"    "validTo must not be in the past"
    Should Be Equal As Numbers    ${response.status_code}    400

Test POST Request With Invalid UnitOfMeasure
    [Documentation]    Test la requête POST avec une unité de mesure invalide.
    Get_token
    ${response}=    Post_invalid_ValidityCharacteristic    Test_Cases/Product/Data/Post_body_for_ValidityCharacteristic.json    unitOfMeasure    400    Invalid body field       Either 'value' and 'unitOfMeasure' must be present together or 'validTo', but not both
    Should Be Equal As Numbers    ${response.status_code}    400

Test POST Request With Missing ValidTo
    [Documentation]    Test la requête POST sans `validTo`.
    Get_token
    ${response}=    Post_valid_return_response    Post_body_for_ValidityCharacteristic
    Should Be Equal As Numbers    ${response.status_code}    201

Test POST Request With Missing UnitOfMeasure
    [Documentation]    Test la requête POST sans `unitOfMeasure`.
    Get_token
    ${response}=    Post_valid_return_response    Post_body_for_ValidityCharacteristic
    Should Be Equal As Numbers    ${response.status_code}    201

Test POST Request With Missing Duration And ValidTo
    [Documentation]    Test la requête POST sans `duration` et `validTo`.
    Get_token
    ${response}=    Post_valid_return_response    Post_body_for_ValidityCharacteristic
    Should Be Equal As Numbers    ${response.status_code}    201

Test POST Request With Duration And UnitOfMeasure And ValidTo (Should Fail)
    [Documentation]    Test la requête POST avec `duration`, `unitOfMeasure` et `validTo` (doit échouer).
    [Tags]  Bug
    Get_token
    ${response}=    Post_invalid_ValidityCharacteristic    Test_Cases/Product/Data/Post_body_for_ValidityCharacteristic.json    duration    400    "Invalid duration"    "Cannot specify both duration and validTo"
    Should Be Equal As Numbers    ${response.status_code}    400

*** Keywords ***

Post_valid_return_response
    [Documentation]    Wrapper for Post_valid that returns the full response object instead of just the ID
    [Arguments]    ${file_name}
    ${uuid}=    Evaluate    uuid.uuid4()    modules=uuid
    ${log-tag}=    Catenate    post-valid-    ${uuid}
    ${log-tag}=    Replace String    ${log-tag}    ${space}    ${empty}
    ${MY_FILE}=    OperatingSystem.Get File    Test_Cases/Product/Data/${file_name}.json
    ${MY_FILE}=    evaluate    json.loads('''${MY_FILE}''')    json
    ${Content_File}    BuiltIn.Convert To String    ${MY_FILE}
    ${json_string}    Global_Keywords.Replace Template Values    ${Content_File}
    ${modified_json_string}    Set Variable    ${json_string.replace('productOrderId_value', '${log-tag}')}
    ${JSON_DATA}=    Evaluate    json.dumps(${modified_json_string})    string
    ${MY_DATA}=    Evaluate    json.loads('''${JSON_DATA}''')    json
    &{headers}=    Create Dictionary    Content-Type=application/json    Accept=*/*    Accept-Encoding=gzip, deflate, br    Connection=keep-alive    Authorization=Bearer ${CPIB_TOKEN}
    Create Session    session    ${end-point-cpib}
    ${response}=    POST Request    session    /productInventoryManagement/v1/product    headers=&{headers}    data=${MY_DATA}
    Run Keyword And Continue On Failure    Should Be Equal As Strings    ${response.status_code}    201
    ${id}    Evaluate    json.loads('''${response.content}''')['id']
    Should Contain    ${response.headers['location']}    ${end-point-cpib}/productInventoryManagement/v1/product/${id}
    RETURN    ${response}

Post_invalid_ValidityCharacteristic
    [Arguments]    ${file}    ${field_verif}    ${code_verif}    ${reason_verif}    ${message_verif}
    ${uuid}=    Evaluate    uuid.uuid4()    modules=uuid
    ${log_tag}=    Catenate    post-invalid-ValidityCharacteristic-    ${uuid}
    ${log_tag}=    Replace String    ${log_tag}    ${space}    ${empty}
    ${MY_FILE}=    OperatingSystem.Get File    ${file}
    ${Content_File}=    Evaluate    json.loads('''${MY_FILE}''')    json
    ${New_Content_File}=    BuiltIn.Convert To String    ${Content_File}
    ${json_string}=    Global_Keywords.Replace Template Values    ${New_Content_File}
    ${modified_json_string}=    Set Variable    ${json_string.replace('productOrderId_value', '${log_tag}')}
    # Modifier en fonction de la vérification
    ${modified_json_string_2}=    Set Variable    ${modified_json_string.replace('${field_verif}', 'incorrect_value')}
    ${JSON_DATA}=    Evaluate    json.dumps(${modified_json_string_2})    string
    ${MY_DATA}=    Evaluate    json.loads('''${JSON_DATA}''')    json
    &{headers}=    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${CPIB_TOKEN}    Accept-Encoding=gzip, deflate, br    Connection=keep-alive
    Create Session    session    ${end-point-cpib}
    ${response}=    POST Request    session    /productInventoryManagement/v1/product    headers=&{headers}    data=${MY_DATA}
    Run Keyword And Continue On Failure    Should Be Equal As Strings    ${response.status_code}    ${code_verif}
    ${Return_response}=    Evaluate    json.loads('''${response.text}''')    json
    Should Be Equal As Strings    ${Return_response['status']}    BAD_REQUEST
    Should Be Equal As Strings    ${Return_response['code']}        24
    Should Be Equal As Strings    ${Return_response['reason']}    ${reason_verif}
    Should Be Equal As Strings    ${Return_response['message']}    ${message_verif}
    RETURN    ${response}
