*** Settings ***
Resource        ../../POST_Method/Keywords/post_usecases.robot
Resource        ../../GET_Method/Keywords/get_usecases.robot
Resource        ../../DELETE_Method/Keywords/delete_usecases.robot
Resource        ../Keywords/patch_usecases.robot

*** Test Cases ***

Check_lastUpdateDate_after_name_change
    Get_token
    ${valid_id}=                Post_valid          Post_body_request_for_Patch
    patch_field                 ${valid_id}         name                                My new name generated by automation
    check_lastUpdateDate        ${valid_id}

Check_lastUpdateDate_after_delete_Product
    ${id}                                   Post_valid_physical                     Post_body_request_for_physical_product
    delete_product                          ${id}[0]
    check_lastUpdateDate                    ${id}[1]
