# SPDX-FileCopyrightText: 2025 - 2026 Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT License,
# the text of which is available at https://opensource.org/license/mit
# or see the "LICENSE.txt" file for more details.
#
# Authors: See CONTRIBUTORS.txt

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Application replica count
replicaCount: 1

# -- Enable or disable application daily shutdown
scheduledshutdown: false

# -- Keystore in P12 format, base64 encoded
keyStoreP12: ""

# -- jdk options to be set on the application container
jdkJavaOptions: ""

# Docker image parameters
image:
  # -- docker image repository
  repository: "${docker_repository}"
  # -- image pull policy
  pullPolicy: Always
  # -- overrides the image tag whose default is the chart appVersion.
  tag: "${docker_tag}"

# -- Specify pulling image secrets if your image repository requires it
imagePullSecrets: []

# Specifies whether a secret should be created for pulling images
registryCredentials:
# -- specifies whether a secret should be created for pulling images from a private registry
  create: false
  # -- the URL of the private registry.
  url: ""
  # -- the access token of the private registry
  token:
    userName: ""
    password: ""

# -- Override default fully qualified app name and chart name
nameOverride: ""

# -- Override fully qualified app name
fullnameOverride: ""

# Specifies whether a service account should be created
serviceAccount:
  # -- specifies whether a service account should be created
  create: true
  # -- annotations to add to the service account
  annotations: {}
  # -- the name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# remove curly braces and specify if necessary
podAnnotations: {}
  # example to enable monitoring and supervision of pods
  # prometheus.io/port: '8080'
  # prometheus.io/scrape: 'true'
# metrics: '/actuator/prometheus' # align with contextPath, if specified

# remove curly braces and specify if necessary
podSecurityContext: {}
  #runAsUser: 1003170001
  #runAsGroup: 1003170001
  # runAsUser: 1000
# fsGroup: 2000

# remove curly braces and specify if necessary
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

# Set to true if you want this chart to create a certificate for you. Default is false.
certManager:
  # -- specify whether a certificate should be created for this service
  create: false

# Service configuration
service:
  type: ClusterIP
  port: 8080
  # -- enable monitoring and supervision of service
  annotations: {}
  #  prometheus.io/port: '9000'
  #  prometheus.io/scrape: 'true'

# Set to true if using ingress to expose your service
ingress:
  # -- Enable ingress controller
  enabled: false
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # Hosts configuration
  hosts:
    - host: ""
      paths: [/] # align with contextPath

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # -- Default resource requests
  requests:
    cpu: 200m
    memory: 256Mi
  # -- Default resource limits
  limits:
    cpu: "1"
    memory: 1Gi

# Horizontal Pod Autoscaler configuration
autoscaling:
  # -- Enable Horizontal Pod Autoscaler
  enabled: false
  # -- Minimum number of pod replicas
  minReplicas: 2
  # -- Maximum number of pod replicas
  maxReplicas: 5
  # -- Target CPU utilization percentages for pod scaling
  targetCPUUtilizationPercentage: 70
  # -- Target Memory utilization percentages for pod scaling
  targetMemoryUtilizationPercentage: ""

# -- Node selectorfor pod assignment
nodeSelector: {}

# -- Node tolerations for pod assignment
tolerations: []

# -- Node affinity for pod assignment
affinity: {}

# OpenTelemetry configuration
otel:
  # -- activate Open Telemetry instrumentation
  enabled: false
  sidecar:
    # -- use collector agent sidecar
    enabled: false
    # -- main collector address
    jaeger:
      # collector host
      host: ""
      # collector port
      port: 14250
    # main receiver address
    otlp:
      # receiver host
      host: ""
      # receiver port
      port: 4317
  # resource attributes to be set on telemetry data
  attributes:
    # -- resource attribute to be set on telemetry data
    platform: ""
    # -- resource attribute to be set on telemetry data
    region: ""
    # -- resource attribute to be set on telemetry data
    cluster: ""
    # -- resource attribute to be set on telemetry data
    namespace: ""
    # -- resource attribute to be set on telemetry data
    hostname: ""

# fluentd sidecar for logs forwarding
fluentd:
  # -- enable fluentd sidecar container
  enabled: false
  # -- tag value being set on log events and used by fluentd to route logs
  tag: ""
  # -- hostname of the fluentd instance this application should send logs to. Defaults to localhost
  host: ""
  # -- port of the fluentd instance this application should send logs to. Defaults to localhost
  port: ""
  sidecar:
    # -- use to enable fluentd sidecar container running logging agent
    enabled: false
    loki:
      # -- URL of the Loki instance that the sidecar will output logs to
      url: ""
      # -- extra labels that the fluentd sidecar will set on log events for loki
      extra_labels: "\"env\":\"sandbox\", \"app\": \"disco\""

# Used to specify labels on pods and services (useful for monitoring)
monitoring:
  # -- label to specify application name
  application: ""
  # -- label to specify application name
  app: ""
  # -- label to specify product name (chart name by default)
  productName: ""
  # -- label for environment being deployed
  environment: ""

# Default hostnames and ports of dependent services
od:
  # -- spring json secret name
  spring_json_secret_name: ""
  service:
    # -- spring json secret name
    spring_json_secret_name: ""
    # -- enable delivery delay
    enableDeliveryDelay: false
    # -- minimal delivery delay
    minDeliveryDelayExpression: ""
    # maximal delivery delay
    maxDeliveryDelayExpression: ""
    # -- max heap memory for application container
    mxHeap: "500M"

services:
  # -- service name of kafka service
  kafka: kafka
  # product catalog service name
  productCatalog: catalog-product-catalog
  # -- service name of product inventory API
  cpib: product-inventory
  # -- service name of order inventory API
  poi: order-inventory
  # -- service name of mock server
  mock: mock-server
  # -- service name of user role & permission API
  userRoleRetrieval: auth-userrole

# Keycloak configuration
keycloak:
  # -- enable or disable Keycloak integration
  enabled: false
  # -- Keycloak client ID
  clientId: ""
  # -- Keycloak client secret
  clientSecret: ""
  # -- Keycloak URL
  uri: ""

# Set the api version in URL path
api:
  # -- Context path for the API endpoint
  contextPath: "/api/v2/"

# -- Set the context path in the API endpoint, for instance /order-follow-up. Default is blank.
contextPath: ""
