apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "productinventoryui.fullname" . }}-config
data:
  GATEWAY_URL: {{ .Values.productinventoryui.service.gatewayUrl | quote }}
  STANDALONE_MODE: {{ .Values.productinventoryui.service.standaloneMode | quote }}