apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orderinventoryui.fullname" . }}-config
data:
  GATEWAY_URL: {{ .Values.orderinventoryui.service.gatewayUrl | quote }}
  STANDALONE_MODE: {{ .Values.orderinventoryui.service.standaloneMode | quote }}