<?xml version="1.0" encoding="UTF-8"?>

<!--
SPDX-FileCopyrightText: 2025 Orange SA
SPDX-License-Identifier: MIT

This software is distributed under the MIT License,
the text of which is available at https://opensource.org/license/mit
or see the "LICENSE.txt" file for more details.

Authors: See CONTRIBUTORS.txt
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.orange.discobole.permission</groupId>
		<artifactId>discobole-permission-user-role-management</artifactId>
		<version>1.4.0</version>
	</parent>
	<groupId>com.orange.discobole.permission</groupId>
	<artifactId>discobole-permission-user-role-management-service</artifactId>
	<name>Userrole management service</name>
	<description>service project of user rule</description>
	<properties>
		<java.version>17</java.version>
		<cucumber.version>4.7.2</cucumber.version>
		<jacoco.version>0.8.8</jacoco.version>
		<sonar.qualitygate.wait>true</sonar.qualitygate.wait>
		<swagger.version>3.0.0</swagger.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.orange.discobole.permission</groupId>
			<artifactId>discobole-permission-user-role-management-spec</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.0.2</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>${swagger.version}</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>${swagger.version}</version>
		</dependency>
		<!--<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>0.11.5</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>0.11.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>0.11.5</version>
		</dependency>

	</dependencies>

	<build>
		<finalName>catalog-userrole</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<!--<plugin>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-codegen-maven-plugin</artifactId>
				<version>2.4.14</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<skip>true</skip>
							<inputSpec>${project.basedir}/src/main/resources/TMF620-ProductCatalog-v4.0.0.swagger.json
							</inputSpec>
							<language>java</language>
							<generateModelDocumentation>false</generateModelDocumentation>
							<generateApis>false</generateApis>
							<generateModelTests>false</generateModelTests>
							<generateSupportingFiles>false</generateSupportingFiles>
							<configOptions>
								<library>jersey2</library>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.1.1</version>
				<executions>
					<execution>
						<id>unpack</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>unpack</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>com.orange.discobole.permission</groupId>
									<artifactId>discobole-permission-user-role-management-spec</artifactId>
									<version>${project.version}</version>
									<type>jar</type>
									<overWrite>false</overWrite>
									<includes>**/*.yaml</includes>
								</artifactItem>
							</artifactItems>
							<outputDirectory>${project.build.directory}/classes/static/api-docs</outputDirectory>
							<overWriteReleases>true</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.10</version>
				<executions>
					<execution>
						<id>jacoco-agent</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
						<configuration>
							<propertyName>surefireArgLine</propertyName>
							<destFile>${project.build.directory}/coverage-reports/jacoco-ut.exec
							</destFile>
						</configuration>
					</execution>
					<execution>
						<id>check</id>
						<goals>
							<goal>check</goal>
						</goals>
						<configuration>
							<skip>true</skip>
							<dataFile>${project.build.directory}/coverage-reports/jacoco-ut.exec
							</dataFile>
							<excludes>
							</excludes>
							<rules>
								<rule implementation="org.jacoco.maven.RuleConfiguration">
									<element>BUNDLE</element>
									<limits>
										<limit>
											<counter>INSTRUCTION</counter>
											<value>COVEREDRATIO</value>
											<minimum>0.80</minimum>
										</limit>
										<limit>
											<counter>CLASS</counter>
											<value>MISSEDCOUNT</value>
											<maximum>0</maximum>
										</limit>
									</limits>
								</rule>
							</rules>
						</configuration>
					</execution>
					<execution>
						<id>jacoco-report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							<dataFile>${project.build.directory}/coverage-reports/jacoco-ut.exec
							</dataFile>
							<outputDirectory>${project.reporting.outputDirectory}/coverage
							</outputDirectory>
							<excludes>

							</excludes>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<argLine>${surefireArgLine}</argLine>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-report-plugin</artifactId>
				<version>3.0.0-M4</version>
				<configuration>
					<aggregate>true</aggregate>
					<alwaysGenerateSurefireReport>false</alwaysGenerateSurefireReport>
					<reportsDirectories>${project.build.directory}/surefire-reports
					</reportsDirectories>
					<outputDirectory>${project.reporting.outputDirectory}/junit
					</outputDirectory>
					<outputName>index</outputName>
				</configuration>
				<executions>
					<execution>
						<phase>test</phase>
						<goals>
							<goal>report-only</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<show>private</show>
					<nohelp>true</nohelp>
					<failOnError>false</failOnError>
				</configuration>
				<executions>
					<execution>
						<id>javadoc</id>
						<phase>test</phase>
						<goals>
							<goal>javadoc</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>sonar</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<sonar.projectName>${project.name}</sonar.projectName>
				<sonar.projectVersion>${project.version}</sonar.projectVersion>
				<sonar.projectKey>${env.SONAR_PROJECT_KEY}</sonar.projectKey>
				<!-- <sonar.projectKey>disco-user-role</sonar.projectKey> -->
				<sonar.sources>src/main/java</sonar.sources>
				<sonar.java.source>1.8</sonar.java.source>
				<sonar.junit.reportPaths>catalog-user-role-service/target/surefire-reports</sonar.junit.reportPaths>
				<sonar.coverage.exclusions>
				</sonar.coverage.exclusions>
				<sonar.cpd.exclusions></sonar.cpd.exclusions>
				<!-- <sonar.jacoco.reportPaths>target/coverage-reports/jacoco-ut.exec</sonar.jacoco.reportPaths> -->
				<sonar.coverage.jacoco.xmlReportPaths>catalog-userrole-service/target/site/coverage/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
			</properties>
		</profile>
	</profiles>
</project>
