{{- if .Values.mongo.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "order_follow_up.fullname" . }}-spring
  labels:
    {{- include "order_follow_up.labels" . | nindent 4 }}
type: Opaque
data:
  spring-db: {{ printf "{\"spring\": {\"data\": {\"mongodb\": { \"host\": \"%s-headless\", \"port\": 27017, \"database\": \"%s\", \"username\": \"%s\", \"password\": \"%s\"}}}}"
    (.Values.mongo.fullnameOverride)
    (.Values.mongo.customUsers | first | dig "database" "order_follow_up")
    (.Values.mongo.customUsers | first | dig "name" "mongo_user")
    (.Values.mongo.customUsers | first | dig "password" "")
                | b64enc }}
    {{- end }}