<?xml version="1.0" encoding="UTF-8"?>

<!--
SPDX-FileCopyrightText: 2025 Orange SA
SPDX-License-Identifier: MIT

This software is distributed under the MIT License,
the text of which is available at https://opensource.org/license/mit
or see the "LICENSE.txt" file for more details.

Authors: See CONTRIBUTORS.txt
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.orange.discobole.orderorchestration</groupId>
        <artifactId>discobole-orderorchestration-orchestration-delivery-commons</artifactId>
        <version>3.5.0-SNAPSHOT</version>
    </parent>

    <artifactId>discobole-orderorchestration-orchestration-delivery-commons-pojo</artifactId>
	<name>ODA - COOD - Orchestration Delivery Commons POJO</name>

    <url>https://gitlab.ow2.org/discobole/disco-oda-components/disco-order-orchestration/orchestration-delivery-commons</url>

    <dependencies>
        <dependency>
            <groupId>org.jsonschema2pojo</groupId>
            <artifactId>jsonschema2pojo-core</artifactId>
            <version>1.2.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.26</version>
        </dependency>
    </dependencies>

</project>
