apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order_capture.fullname" . }}
  labels:
    {{- include "order_capture.labels" . | nindent 4 }}
    {{- include "order_capture.shutdownLabels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "order_capture.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "order_capture.selectorLabels" . | nindent 8 }}
        {{- include "order_capture.monitoringLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "order_capture.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: order-capture
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: #modified
            - name: JDK_JAVA_OPTIONS
              value: {{ .Values.jdkJavaOptions }}
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLED
              value: "true"
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                secretKeyRef:
                  name: {{ template "order_capture.fullname" . }}-spring
                  key: spring-db
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_SOURCES_0_NAME
              value: "{{ template "order_capture.fullname" . }}"
            - name: SPRING_PROFILES_ACTIVE
              value: jsonconsole{{- if .Values.fluentd.enabled }},fluentd{{- end }}
            - name: KAFKA_SERVICE
              value: {{ .Values.services.kafka }}
            - name: ENV_TYPE
              value: {{ .Values.environmentType }}
            - name: PRODUCT_CATALOG_SERVICE
              value: {{ .Values.services.productCatalog }}
            - name: PRODUCT_CONFIGURATOR_SERVICE
              value: {{ .Values.services.productConfigurator }}
            - name: MOCK_SERVER_SERVICE
              value: {{ .Values.services.mockServer }}
            - name: PRODUCT_INVENTORY_SERVICE
              value: {{ .Values.services.productInventory }}
            - name: AUTH_USER_ROLE_SERVICE
              value: {{ .Values.services.authUserRole }}
            {{- if .Values.keycloak.enabled }}
            - name: ORDER_KEYCLOAK_CLIENT_ID
              value: {{ .Values.keycloak.clientId }}
            - name: ORDER_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oc-keycloak-client-secret-{{ .Values.environmentType }}
                  key: ORDER_KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloak.url }}
            {{- end }}
            - name: ORDER_INVENTORY_SERVICE
              value: {{ .Values.services.orderInventory }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "{{ .Values.contextPath }}"
            {{- if .Values.fluentd.enabled }}
            - name: FLUENTD_TAG
              value: "{{ default "order_capture" .Values.fluentd.tag }}"
            - name: FLUENTD_CONTAINER_NAME
              value: "order_capture"
            - name: FLUENTD_HOST
              value: "{{ default "localhost" .Values.fluentd.host }}"
            - name: FLUENTD_PORT
              value: "{{ default "24224" .Values.fluentd.port }}"
            {{- end }}
            {{- if .Values.otel.enabled }}
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/opentelemetry-javaagent.jar -Dotel.instrumentation.kafka.enabled=true -Dotel.instrumentation.spring-kafka.enabled=true -Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=false -Xlog:gc=debug:file=/tmp/gc.ordercapture.log:time,uptime,level,tags:filecount=5,filesize=100m -XX:MaxMetaspaceSize=256m -XX:+UseG1GC -XX:+CrashOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump-ordercapture.log{{- if .Values.oc.service.mxHeap }} -XX:MaxHeapSize={{ .Values.oc.service.mxHeap }}{{- end }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://{{ .Values.otel.sidecar.otlp.host }}:{{ .Values.otel.sidecar.otlp.port }}"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: "{{ template "order_capture.fullname" . }}"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name={{ include "order_capture.fullname" . }},app=lizard,deployment.environment={{ default "undefined" .Values.monitoring.environment }},cloud.platform={{ default "undefined" .Values.otel.attributes.platform }},cloud.region={{ default "undefined" .Values.otel.attributes.region }},host.name={{ default "undefined" .Values.otel.attributes.hostname }},k8s.cluster.name={{ default "undefined" .Values.otel.attributes.cluster }},k8s.namespace.name={{ default "undefined" .Values.otel.attributes.namespace }},container_name=order_capture"
            {{- end }}
          ports:
            - name: http
              containerPort: 8080 #modified
              protocol: TCP
            - name: actuator
              containerPort: 9000 #modified
              protocol: TCP
          volumeMounts:
            - name: {{ template "order_capture.fullname" . }}-applog
              mountPath: /tmp
            - name: volume-keystore
              mountPath: /mnt/keystore
              readOnly: true
          readinessProbe:
            httpGet:
              path: {{ .Values.contextPath }}/actuator/health/readiness
              port: actuator
            initialDelaySeconds: 65
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.contextPath }}/actuator/health/liveness
              port: actuator
            initialDelaySeconds: 200
            failureThreshold: 1
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: {{ .Values.contextPath }}/actuator/health
              port: actuator
            initialDelaySeconds: 100
            failureThreshold: 45
            periodSeconds: 2
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ template "order_capture.fullname" . }}-applog
          emptyDir: { }
        - name: volume-keystore
          secret:
            secretName: {{ include "order_capture.fullname" . }}-keystore-p12
            items:
              - key: keystore-p12
                path: keystore-p12
            defaultMode: 420
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}