*** Settings ***
Resource        ../Keywords/get_JobSpecifications_usecases.robot
Resource        ../Keywords/post_JobSpecifications_usecases.robot

*** Test Cases ***

Filtering_JobSpecifications_by_ExportJobSpecification_ID
    Get_token
    ${Valid_ExportJobSpecification_JobSpecification_id}=        Post_JobSpecification_with_QueryStatus      ExportJobSpecification          Created     Post_ExportJobSpecification_JobSpecification_body_request
    get_valid_field_JobSpecification             id             ${Valid_ExportJobSpecification_JobSpecification_id}

Filtering_JobSpecifications_by_PurgeJobSpecification_ID
    Get_token
    ${Valid_PurgeJobSpecification_JobSpecification_id}=         Post_JobSpecification_with_QueryStatus      PurgeJobSpecification           Cancelled         Post_PurgeJobSpecification_JobSpecification_for_Products_body_request
    get_valid_field_JobSpecification             id             ${Valid_PurgeJobSpecification_JobSpecification_id}

Filtering_JobSpecifications_by_nonExistent_ID
    get_bad_field_JobSpecification               id             worng_id

Filtering_JobSpecifications_by_empty_ID
    get_empty_field_JobSpecification             id             ${EMPTY}        ${code_28}       ${invalid_paramter_reason}        id must not be empty

Filtering_JobSpecifications_by_Name
    Get_token
    ${Valid_task_name}      Set Variable            JobSpecification generated by automation ツ
    get_valid_field_JobSpecification                name           ${Valid_task_name}

Filtering_JobSpecifications_by_nonExistent_Name
    get_bad_field_JobSpecification               name           worng_name

Filtering_JobSpecifications_by_empty_Name
    get_empty_field_JobSpecification             name           ${EMPTY}        ${code_28}       ${invalid_paramter_reason}        name must not be empty

Filtering_JobSpecifications_by_TerminationJobSpecification_@type
    get_valid_field_JobSpecification             @type          TerminationJobSpecification

Filtering_JobSpecifications_by_nonExistent_@type
    get_bad_field_JobSpecification               @type          worng_@type

Filtering_JobSpecifications_by_empty_@type
    get_empty_field_JobSpecification             @type          ${EMPTY}        ${code_28}       ${invalid_paramter_reason}        @type must not be empty
