{{- if .Values.registryCredentials.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred-{{ template "selfcareui.fullname" . }}
  labels:
    {{- include "selfcareui.labels" . | nindent 4 }}
data:
  .dockerconfigjson: >-
    {{ template "selfcareui.regcredData" . }}
{{- end }}
