apiVersion: v1
kind: Secret
metadata:
  name: {{ include "selfcareui.fullname" . }}-secrets
  labels:
    {{- include "selfcareui.labels" . | nindent 4 }}
type: Opaque
stringData:
  EXPRESS_APP_USERNAME: {{ .Values.keycloak.username | quote }}
  EXPRESS_APP_PASSWORD: {{ .Values.keycloak.password | quote }}
  EXPRESS_APP_CLIENT_SECRET: {{ .Values.keycloak.clientSecret | quote }}
  EXPRESS_APP_ADMIN_USERNAME: {{ .Values.keycloak.adminUsername | quote }}
  EXPRESS_APP_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
  EXPRESS_APP_SERVICE_CLIENT_ID: {{ .Values.keycloak.serviceClientId | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  INTERNAL_SECRET: {{ .Values.secrets.internalSecret | quote }}