<?xml version="1.0" encoding="UTF-8"?>

<!--
SPDX-FileCopyrightText: 2025 Orange SA
SPDX-License-Identifier: MIT

This software is distributed under the MIT License,
the text of which is available at https://opensource.org/license/mit
or see the "LICENSE.txt" file for more details.

Authors: See CONTRIBUTORS.txt
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.orange.discobole.orderorchestration</groupId>
        <artifactId>discobole-orderorchestration-orchestration-delivery-spec</artifactId>
        <version>1.6.0</version>
    </parent>

    <artifactId>discobole-orderorchestration-orchestration-delivery-restapi-spec</artifactId>
    <name>ODA - COOD - Orchestration Delivery API REST Specification</name>

    <url>https://gitlab.ow2.org/discobole/disco-oda-components/disco-order-orchestration/orchestration-delivery-spec/</url>

    <properties>
        <swaggerFileOrchestrationDelivery>${project.basedir}/src/main/resources/orchestration-delivery-spec.yaml</swaggerFileOrchestrationDelivery>
        <swaggerFileLeadTimeStatistics>${project.basedir}/src/main/resources/lead-time-statistics.yaml</swaggerFileLeadTimeStatistics>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-classes-orchestrationdelivery</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${swaggerFileOrchestrationDelivery}</inputSpec>
                            <generatorName>spring</generatorName>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <interfaceOnly>true</interfaceOnly>
                                <dateLibrary>java8</dateLibrary>
                                <!-- lombok related config -->
                                <generatedConstructorWithRequiredArgs>false</generatedConstructorWithRequiredArgs>
                                <additionalModelTypeAnnotations>@lombok.experimental.Accessors(chain = true);@lombok.NoArgsConstructor;@lombok.AllArgsConstructor;@lombok.experimental.SuperBuilder;@lombok.experimental.FieldNameConstants;@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY)</additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>com.orange.discobole.orderorchestration.orchestrationdelivery.api.v1</apiPackage>
                            <modelPackage>com.orange.discobole.orderorchestration.orchestrationdelivery.dto.v1</modelPackage>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-classes-lead-time-statistics</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${swaggerFileLeadTimeStatistics}</inputSpec>
                            <generatorName>spring</generatorName>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <interfaceOnly>true</interfaceOnly>
                                <dateLibrary>java8</dateLibrary>
                                <!-- lombok related config -->
                                <generatedConstructorWithRequiredArgs>false</generatedConstructorWithRequiredArgs>
                                <additionalModelTypeAnnotations>@lombok.experimental.Accessors(chain = true);@lombok.NoArgsConstructor;@lombok.AllArgsConstructor;@lombok.experimental.SuperBuilder;@lombok.experimental.FieldNameConstants;@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY)</additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>com.orange.discobole.orderorchestration.orchestrationdelivery.leadtimestatistics.api.v1</apiPackage>
                            <modelPackage>com.orange.discobole.orderorchestration.orchestrationdelivery.leadtimestatistics.dto.v1</modelPackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>