{{- if or .Values.mongo.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestration_delivery_fallout.fullname" . }}-spring
  labels:
    {{- include "orchestration_delivery_fallout.labels" . | nindent 4 }}
type: Opaque
data:
  spring-db: {{ printf "{\"spring\": {\"data\": {\"mongodb\": { \"uri\": \"mongodb://%s:%s@%s:27017/%s?replicaSet=rs0\", \"database\": \"%s\"}}}}"
    (.Values.mongo.customUsers | first | dig "name" "mongo_user")
    (.Values.mongo.customUsers | first | dig "password" "")
    (printf "%s-headless" .Values.mongo.fullnameOverride)
    (.Values.mongo.customUsers | first | dig "database" "orchestration_delivery_fallout")
    (.Values.mongo.customUsers | first | dig "database" "orchestration_delivery_fallout")
                | b64enc | quote }}
    {{- end }}