# Software Name: disco-tmf688
# SPDX-FileCopyrightText: 2025 Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT License,
# the text of which is available at https://opensource.org/license/mit
# or see the "LICENSE.txt" file for more details.
#
# Authors: See CONTRIBUTORS.txt
# Software description: Provides a standardized client interface to the enterprise event management system

# ==================================================
# Pipeline templates
# ==================================================
include:
  - project: 'discobole/discobole-to-be-continuous/service'
    ref: 'main'
    file: '/templates/gitlab-ci-service.yml'

# ==================================================
# Pipeline stages
# ==================================================
stages:
  - debug
  - build
  - test
  - package-build
  - package-test
  - infra
  - deploy
  - acceptance
  - publish
  - infra-prod
  - production

# ==================================================
# Pipeline variables
# ==================================================
variables:
  MAVEN_BUILD_ARGS: -DskipTests package

