server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: billing-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/billing_service?replicaSet=rs0}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:${server.port}}
  endpoints:
    web:
      exposure:
        include: health,info

simulator:
  failure-mode: ${SIMULATOR_FAILURE_MODE:success}
